[database]
# address = "db"
address = "127.0.0.1"
port = "3306"
user = "root"
password = "password"
database = "maplestory"

[login]
clientListenAddress = "0.0.0.0"
clientListenPort = "8484"
serverListenAddress = "0.0.0.0"
serverListenPort = "8485"
packetQueueSize = 10

[world]
listenPort = "8584"
packetQueueSize = 10

[channel]
listenAddress = "0.0.0.0"
listenPort = "8684"
packetQueueSize = 10