version: '3.1'

services:
    login-server:
        image: valhalla/server
        build:
            context: ./
            dockerfile: docker/Dockerfile
        command: -type=login
        environment:
            - DB_USER=root
            - DB_PASSWORD=password
            - DB_DATABASE=maplestory
            - DB_ADDRESS=db
            - DB_PORT=3306
        ports:
            - 8484:8484
        restart: always

    channel-server:
        image: valhalla/server
        command: -type=channel
        volumes:
            - ./Data.nx:/app/Data.nx
        environment:
            - DB_USER=root
            - DB_PASSWORD=password
            - DB_DATABASE=maplestory
            - DB_ADDRESS=db
            - DB_PORT=3306
        ports:
            - 8686:8686
        restart: always
        
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=maplestory
        restart: always

    adminer:
        image: adminer
        ports:
            - 8080:8080
        restart: always

    # elasticsearch:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    #     container_name: elasticsearch
    #     volumes:
    #         - esdata:/usr/share/elasticsearch/data
    #     ports:
    #         - 9200:9200
    #     restart: always
    
    # grafana:
    #     image: grafana/grafana
    #     ports:
    #         - "3000:3000"   

volumes:
    db-data:
    esdata: